### ISSUE TITLE
panel: Verifying FQDN when it's IP

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#133]
**Describe the bug**
The new `verify-fqdn.sh` script runs on IP's and gives an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the script
2. Choose to install panel
3. Enter `FQDN` as IP
4. See that it can't access that IP.

**Expected behaviour**
It shouldn't verify IP's

**OS:**
 - OS: All
 - Installation: panel

**Additional context**
Also, not related to that, you should add `-q` flag to package managers not to disrupt the experience.

**Comment by vilhelmprytz** [comment]
Thanks for reporting this. I've just pushed a commit to master, can you try the canary version to see if it works better?

**Comment by Linux123123** [comment]
It might work on external IP's (haven't tested that), but I am using the vagrant image and local IP's are still a problem.

**Comment by vilhelmprytz** [comment]
Alright. Perhaps it's better to move the `verify-fqdn` check to only run if the user uses the automatic Let's Encrypt setup. That's the only case where we really want to verify the FQDN, right?

**Comment by Linux123123** [comment]
Also for assume SSL maybe?

**Comment by vilhelmprytz** [comment]
I've pushed another commit with your suggested changes. Should be all good now!

**Comment by vilhelmprytz** [comment]
Perhaps this https://github.com/vilhelmprytz/pterodactyl-installer/blob/0365b41a6a86f84106a8b07ec2f55b8d976b2e36/lib/verify-fqdn.sh#L82 should be removed now since IPs should not be valid when using Let's Encrypt or other SSL.

**Comment by Linux123123** [comment]
Yes exactly.
